config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/static_pages/home"
    get "/static_pages/help"
    get "/static_pages/contact"

    get "/categories/index"
    get "/categories/show"

    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    
    get "/search", to: "search#index"

    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    devise_for :users
    as :user do
      get "signin" => "devise/sessions#new"   
      post "signin" => "devise/sessions#create" 
      delete "signout" => "devise/sessions#destroy"
    end
    resources :users do
      resources :addresses, except: :show
      resources :orders, only: %i(index order_details) do
        get 'order_details', to: 'orders#order_details', as: :order_details
        member do
          patch :cancel
        end
        resources :products, only: [] do
          resources :reviews, only: %i(new create edit update destroy)
        end
        collection do
          get :status, action: :index
        end
      end
      resources :notifications, only: [] do
        member do
          patch :mark_as_read
        end
      end
    end
    resources :categories do
      resources :products
    end
    resources :carts, only: :show do
      post "add_item", on: :collection
      member do
        post "increment_item"
        post "decrement_item"
        delete "remove_item"
      end
    end
    resources :products, only: %i(show index)
    resources :password_resets, only: %i(new create edit update)
    resources :orders, only: %i(new create show) 
    namespace :admin do
      get "profile", to: "dashboard#profile", as: "profile"
      get "dashboard", to: "dashboard#index", as: "dashboard"
      resources :orders
      resources :users do
        member do
          patch :toggle_activation
        end
      end
      resources :products
      resources :categories
      resources :reviews
    end
  end
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < Admin::AdminController
  include Pagy::Backend
  before_action :find_review, only: %i(show destroy)

  def index
    @pagy, @reviews = pagy search_reviews
  end

  def show
    @reviews = Review.where(product_id: @review.product_id)
  end

  def destroy
    ActiveRecord::Base.transaction do
      @review.destroy!
      flash[:success] = t "admin.reviews_admin.destroy.success"
      redirect_to admin_reviews_path(@product)
    end
  rescue ActiveRecord::RecordNotDestroyed
    flash[:alert] = t "admin.reviews_admin.destroy.failure"
    redirect_to admin_reviews_path(@product)
  end

  private

  def find_review
    @review = Review.find_by(id: params[:id])
    return if @review

    flash[:alert] = t "admin.reviews_admin.not_found"
    redirect_to admin_reviews_path(@product)
  end

  def search_reviews
    reviews = Review.all
    reviews = filter_reviews_by_query(reviews)
    reviews = filter_reviews_by_rating(reviews)
    sort_reviews(reviews)
  end

  def filter_reviews_by_query reviews
    query = params[:query]
    if query.present?
      reviews.joins(:user, :product).where(
        "LOWER(users.user_name) LIKE LOWER(:query) OR
       LOWER(products.name) LIKE LOWER(:query)",
        query: "%#{query.downcase}%"
      )
    else
      reviews
    end
  end

  def filter_reviews_by_rating reviews
    rating = params[:rating]
    if rating.present?
      reviews.by_rating(rating)
    else
      reviews
    end
  end

  def sort_reviews reviews
    if params[:sort].blank?
      reviews
    else
      reviews.public_send("sort_by_#{params[:sort]}", params[:direction])
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_user, :logged_in_user, :correct_user,
                only: %i(new create edit update destroy)
  before_action :find_order, :find_product, :check_order_delivered,
                only: %i(new create edit update destroy)
  before_action :find_review, only: %i(edit update destroy)
  before_action :check_review, only: %i(new create)

  def new
    @review = @product.reviews.build
  end

  def create
    @review = @product.reviews.build(review_params)
    @review.user = current_user
    @review.order = @order
    if @review.save
      @product.update_average_rating
      flash[:success] = t "reviews.success"
      redirect_to user_order_order_details_path(current_user, @order)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @review.update(review_params)
      @product.update_average_rating
      flash[:success] = t "reviews.updated"
      redirect_to user_order_order_details_path(current_user, @order)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @review.destroy
    @product.update_average_rating
    flash[:success] = t "reviews.destroyed"
    redirect_to user_order_order_details_path(current_user, @order)
  end

  private

  def check_order_delivered
    return if @order&.delivered?

    flash[:danger] = t("reviews.must_be_delivered")
    redirect_to root_path
  end

  def find_review
    @review = @product.reviews.find_by id: params[:id]
    return if @review

    flash[:danger] = t "reviews.review_not_exist"
    redirect_to root_path
  end

  def find_order
    @order = current_user.orders.find_by id: params[:order_id]
    return if @order

    flash[:danger] = t "reviews.order_not_exist"
    redirect_to root_path
  end

  def find_product
    @order_item = @order.order_items.find_by(product_id: params[:product_id])
    @product = @order_item&.product

    return if @product.present?

    flash[:danger] = t "reviews.product_not_exist"
    redirect_to root_path
  end

  def check_review
    existing_review = @product.reviews.find_by(user_id: current_user.id,
                                               order_id: @order.id)

    return if existing_review.blank?

    flash[:danger] = t "reviews.already_reviewed"
    redirect_to root_path
  end

  def review_params
    params.require(:review).permit Review::REVIEW_REQUIRE_ATTRIBUTES
  end

  def find_user
    @user = User.find_by(id: params[:user_id])

    return if @user.present?

    flash[:danger] = t "reviews.user_not_exist"
    redirect_to root_path
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def review_star_rating rating
    stars = (1..5).map do |i|
      class_name = i <= rating ? "text-yellow-500" : "text-gray-300"
      content_tag(:span, "★", class: class_name)
    end

    safe_join(stars)
  end
end

app/views/admin/reviews/_product_item.html.erb
<tr class="border-b border-gray-200 hover:bg-gray-100">
  <td class="py-3 px-6 text-left whitespace-nowrap">
    <div class="flex items-center">
      <span class="font-medium"><%= index %></span>
    </div>
  </td>
  <td class="py-3 px-6 text-left">
    <%= link_to product.name, admin_product_path(product), class: "text-blue-600 hover:underline" %>
  </td>
  <td class="py-3 px-6 text-left">
    <%= product.category.name if product.category %>
  </td>
  <td class="py-3 px-6 text-left">
    <%= number_to_currency(product.price, unit: "", precision: 0) %> ₫
  </td>
  <td class="py-3 px-6 text-left">
    <%= product.created_at.strftime("%d-%m-%Y") %>
  </td>
</tr>

app/views/admin/reviews/_review_item.html.erb
<tr class="border-b border-gray-200 hover:bg-gray-100">
  <td class="py-3 px-6 text-left whitespace-nowrap">
    <div class="flex items-center">
      <span class="font-medium"><%= index %></span>
    </div>
  </td>
  <td class="py-3 px-6 text-left">
    <%= link_to review.product.name, admin_product_path(review.product), class: "text-blue-600 hover:underline" %>
  </td>
  <td class="py-3 px-6 text-left">
    <%= link_to review.user.user_name, admin_user_path(review.user), class: "text-blue-600 hover:underline" %>
  </td>
  <td class="py-3 px-6 text-left">
    <%= review.rating %>
  </td>
  <td class="py-3 px-6 text-left">
    <%= review.comment %>
  </td>
  <td class="py-3 px-6 text-left">
    <%= review.created_at.strftime("%d-%m-%Y") %>
  </td>
  <td class="py-3 px-6 text-center">
    <div class="flex items-center justify-center">
      <%= link_to admin_review_path(review), class: "w-4 mr-2 transform hover:text-blue-600 hover:scale-110" do %>
        <i class="fa fa-eye text-blue-600"></i>
      <% end %>
      <%= button_to admin_review_path(review), method: :delete, data: { turbo_confirm: t("admin.reviews_admin.index.delete_sure") }, class: "w-4 mr-2 transform hover:text-red-600 hover:scale-110" do %>
        <i class="fa fa-trash text-red-600"></i>
      <% end %>
    </div>
  </td>
</tr>

app/views/admin/reviews/_user_item.html.erb
<tr class="border-b border-gray-200 hover:bg-gray-100">
  <td class="py-3 px-6 text-left whitespace-nowrap">
    <div class="flex items-center">
      <span class="font-medium"><%= index %></span>
    </div>
  </td>
  <td class="py-3 px-6 text-left">
    <% if user.activated? %>
      <%= link_to user.user_name, admin_user_path(user), class: "text-blue-600 hover:underline" %>
    <% else %>
      <span class="text-gray-400"><%= user.user_name %></span>
    <% end %>
  </td>
    <td class="py-3 px-6 text-left">
    <%= user.email %>
  </td>
  <td class="py-3 px-6 text-left">
    <%= user.role.present? ? t("admin.users_admin.index.roles.#{user.role}") : "" %>
  </td>
  <td class="py-3 px-6 text-left">
    <%= user.activated? ? t("admin.users_admin.index.activated") : t("admin.users_admin.index.inactivated") %>
  </td>
</tr>

app/views/admin/reviews/index.html.erb
<div class="h-full ml-14 mb-10 md:ml-64" style="padding-top: 110px;">
  <h1 class="text-3xl font-bold mb-6"><%= t "admin.reviews_admin.index.title" %></h1>

  <div class="flex justify-between mb-4">
    <div class="flex items-center">
      <%= form_with url: admin_reviews_path, method: :get, local: true do %>
        <input type="text" name="query" placeholder="<%= t 'admin.reviews_admin.index.search_placeholder' %>" class="border rounded-lg py-2 px-4 mr-2" value="<%= params[:query] %>" style="width: 350px;" />
        <select name="rating" class="border rounded-lg py-2 px-4 mr-2" style="width: 150px;">
          <option value=""><%= t "admin.reviews_admin.index.all_ratings" %></option>
          <% (1..5).each do |star| %>
            <option value="<%= star %>" <%= "selected" if params[:rating].to_i == star %>><%= star %> <%= t "admin.reviews_admin.index.star" %></option>
          <% end %>
        </select>

        <button type="submit" class="bg-primary text-white py-2 px-4 rounded-lg hover:bg-primary_hover"><%= t "admin.reviews_admin.index.search" %></button>
      <% end %>
    </div>
    <%= link_to admin_reviews_path, class: "text-black hover:text-gray-400" do %>
      <i class="fa fa-sync-alt"></i>
    <% end %>
  </div>

  <table class="min-w-full bg-white border rounded-lg shadow-md overflow-hidden table-fixed">
    <thead>
      <tr class="bg-primary text-white uppercase text-sm leading-normal">
        <th class="py-3 px-6 text-left w-1/12 border-r border-gray-200">
          <%= t "admin.reviews_admin.index.review_id" %>
        </th>
        <th class="py-3 px-6 text-left w-3/12 border-r border-gray-200">
          <%= t "admin.reviews_admin.index.product_name" %>
        </th>
        <th class="py-3 px-6 text-left w-3/12 border-r border-gray-200">
          <%= t "admin.reviews_admin.index.user_name" %>
        </th>
        <th class="py-3 px-6 text-left w-1/12 border-r border-gray-200">
          <div class="flex justify-between items-center">
            <span class="flex-grow"><%= t "admin.reviews_admin.index.rating" %></span>
            <%= link_to admin_reviews_path(sort: "rating", direction: params[:direction] == "asc" ? "desc" : "asc"), class: "text-white hover:text-gray-400 ml-2" do %>
              <i class="fa fa-sort-alpha-<%= params[:direction] == 'asc' ? 'up' : 'down' %>"></i>
            <% end %>
          </div>
        </th>
        <th class="py-3 px-6 text-left w-2/12 border-r border-gray-200">
          <%= t "admin.reviews_admin.index.comment" %>
        </th>
        <th class="py-3 px-6 text-left w-2/12 border-r border-gray-200">
          <div class="flex justify-between items-center">
            <span class="flex-grow"><%= t "admin.reviews_admin.index.created_at" %></span>
            <%= link_to admin_reviews_path(sort: "created_at", direction: params[:direction] == "asc" ? "desc" : "asc"), class: "text-white hover:text-gray-400 ml-2" do %>
              <i class="fa fa-sort-alpha-<%= params[:direction] == 'asc' ? 'up' : 'down' %>"></i>
            <% end %>
          </div>
        </th>
        <th class="py-3 px-6 text-center w-2/12">
          <%= t "admin.reviews_admin.index.actions" %>
        </th>
      </tr>
    </thead>
    <tbody class="text-gray-600 text-sm font-light">
      <% @reviews.each_with_index do |review, index| %>
        <%= render partial: "admin/reviews/review_item", locals: { review: review, index: index + 1 } %>
      <% end %>
    </tbody>
  </table>

  <div style="display: flex; justify-content: center;">
    <%= render "pagy/pagy_nav", pagy: @pagy %>
  </div>
</div>

app/views/admin/reviews/show.html.erb
<div class="h-full ml-14 mb-10 md:ml-64" style="padding-top: 110px;">
  <h1 class="text-3xl font-bold mb-6 text-center"><%= t "admin.reviews_admin.show.title", review_id: @review.id %></h1>

  <div class="bg-white p-6 rounded-lg shadow-md mb-6">
    <h2 class="text-xl font-semibold mb-4 border-b pb-2"><%= t "admin.reviews_admin.show.review_info" %></h2>
    <h3 class="text-lg font-semibold mb-2"><%= t "admin.reviews_admin.show.user_info" %></h3>
    <div class="mb-6"> 
      <table class="min-w-full bg-white border rounded-lg shadow-md overflow-hidden table-fixed">
        <thead>
          <tr class="bg-primary text-white uppercase text-sm leading-normal">
            <th class="py-3 px-6 text-left w-1/12"><%= t "admin.users_admin.index.user_id" %></th>
            <th class="py-3 px-6 text-left w-4/12"><%= t "admin.users_admin.index.user_name" %></th>
            <th class="py-3 px-6 text-left w-4/12"><%= t "admin.users_admin.index.email" %></th>
            <th class="py-3 px-6 text-left w-2/12"><%= t "admin.users_admin.index.role" %></th>
            <th class="py-3 px-6 text-left w-1/12"><%= t "admin.users_admin.index.status" %></th>
          </tr>
        </thead>
        <tbody class="text-gray-600 text-sm font-light">
          <% @reviews.each_with_index do |review, index| %>
            <%= render partial: "admin/reviews/user_item", locals: { user: review.user, index: index + 1 } %>
          <% end %>
        </tbody>
      </table>
    </div>
    <h3 class="text-lg font-semibold mb-2"><%= t "admin.reviews_admin.show.product_info" %></h3>
    <div class="mb-6">
      <table class="min-w-full bg-white border rounded-lg shadow-md overflow-hidden table-fixed">
        <thead>
          <tr class="bg-primary text-white uppercase text-sm leading-normal">
            <th class="py-3 px-6 text-left w-1/12"><%= t "admin.products_admin.index.product_id" %></th> 
            <th class="py-3 px-6 text-left w-4/12"><%= t "admin.products_admin.index.name" %></th> 
            <th class="py-3 px-6 text-left w-4/12"><%= t "admin.products_admin.index.category" %></th> 
            <th class="py-3 px-6 text-left w-2/12"><%= t "admin.products_admin.index.price" %></th> 
            <th class="py-3 px-6 text-left w-1/12"><%= t "admin.products_admin.index.create_at" %></th> 
          </tr>
        </thead>
        <tbody class="text-gray-600 text-sm font-light">
          <% @reviews.each_with_index do |review, index| %>
            <%= render partial: "admin/reviews/product_item", locals: { product: review.product, index: index + 1 } %>
          <% end %>
        </tbody>
      </table>
    </div>

    <p class="font-medium mb-2"><strong><%= t "admin.reviews_admin.show.rating" %>:</strong> <%= @review.rating %> <i class="fas fa-star text-yellow-500"></i></p>
    <p class="font-medium mb-2" style="min-height: 4.5rem;"><strong><%= t "admin.reviews_admin.show.comment" %>:</strong> <%= @review.comment %></p>
    <p class="font-medium mb-2"><strong><%= t "admin.reviews_admin.show.created_at" %>:</strong> <%= @review.created_at.strftime("%d-%m-%Y") %></p>
  </div>

  <div class="mt-6 flex justify-end space-x-4">
    <%= link_to t("admin.reviews_admin.show.back"), admin_reviews_path, class: "bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded-lg" %>
  </div>
</div>