config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/static_pages/home"
    get "/static_pages/help"
    get "/static_pages/contact"

    get "/categories/index"
    get "/categories/show"

    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    
    get "/search", to: "search#index"

    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    devise_for :users
    as :user do
      get "signin" => "devise/sessions#new"   
      post "signin" => "devise/sessions#create" 
      delete "signout" => "devise/sessions#destroy"
    end
    resources :users do
      resources :addresses, except: :show
      resources :orders, only: %i(index order_details) do
        get 'order_details', to: 'orders#order_details', as: :order_details
        member do
          patch :cancel
        end
        resources :products, only: [] do
          resources :reviews, only: %i(new create edit update destroy)
        end
        collection do
          get :status, action: :index
        end
      end
      resources :notifications, only: [] do
        member do
          patch :mark_as_read
        end
      end
    end
    resources :categories do
      resources :products
    end
    resources :carts, only: :show do
      post "add_item", on: :collection
      member do
        post "increment_item"
        post "decrement_item"
        delete "remove_item"
      end
    end
    resources :products, only: %i(show index)
    resources :password_resets, only: %i(new create edit update)
    resources :orders, only: %i(new create show) 
    namespace :admin do
      get "profile", to: "dashboard#profile", as: "profile"
      get "dashboard", to: "dashboard#index", as: "dashboard"
      resources :orders
      resources :users do
        member do
          patch :toggle_activation
        end
      end
      resources :products
      resources :categories
      resources :reviews
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  UPDATE_ORDER = %i(address_id total status cancel_reason
payment_method).freeze
  UPDATE_ORDER_ADMIN = %i(status cancel_reason payment_method).freeze
  belongs_to :user
  belongs_to :address
  has_many :order_items, dependent: :destroy
  has_many :products, through: :order_items
  enum status: {
    pending: 0,
    confirmed: 1,
    preparing: 2,
    delivering: 3,
    delivered: 4,
    cancelled: 5
  }

  validates :total, presence: true,
    numericality: {greater_than_or_equal_to: Settings.value.min_numeric}
  validates :status, presence: true
  validates :cancel_reason, presence: true, if: ->{cancelled?}

  after_update :send_order_notification
  after_create :send_order_notification

  scope :ordered_by_updated_at, ->{order(updated_at: :desc)}

  scope :by_username, lambda {|user_name|
    joins(:user).where(users: {user_name:}) if user_name.present?
  }

  scope :by_status, ->(status){where(status:) if status.present?}

  scope :sorted, lambda {|sort_column, sort_direction|
    valid_columns = %w(created_at total)
    if valid_columns.include?(sort_column)
      order("#{sort_column} #{sort_direction}")
    else
      order("created_at desc")
    end
  }
  scope :total_revenue, ->{where(status: "delivered").sum(:total)}

  scope :with_status, lambda {|status|
                        where(status:) if statuses.key?(status)
                      }

  def send_order_notification
    Notification.create!(
      user:,
      order: self,
      message: "order.updated",
      read: false,
      status:
    )
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::AdminController
  include Pagy::Backend
  before_action :find_order, only: %i(show edit update)

  def index
    @pagy, @orders = pagy(
      filtered_orders
        .by_username(params[:user_name])
        .sorted(params[:sort], params[:direction])
    )
  end

  def show
    @product = @order.products
  end

  def edit; end

  def update
    ActiveRecord::Base.transaction do
      handle_cancel_order if cancel_reason_present?
      @order.update!(order_params)
      @order.address.update!(address_params)
      flash[:success] = t("admin.orders_admin.update.success")
      @order.user.send_order_update_email @order
      redirect_to admin_order_path(@order)
    rescue ActiveRecord::RecordInvalid => e
      handle_update_error(e)
    end
  end

  private

  def find_order
    @order = Order.find_by(id: params[:id])
    return if @order

    flash[:alert] = t ".not_found"
    redirect_to root_path
  end

  def order_params
    params.require(:order).permit Order::UPDATE_ORDER_ADMIN
  end

  def address_params
    params.require(:order).require(:address).permit(
      Address::ADDRESS_REQUIRE_ATTRIBUTES
    )
  end

  def cancel_reason_present?
    params[:order][:cancel_reason].present?
  end

  def handle_cancel_order
    @order.cancel_reason = params[:order][:cancel_reason]
    @order.cancelled!
    restore_product_stock
  end

  def restore_product_stock
    @order.order_items.each do |order_item|
      order_item.product.increment!(:stock, order_item.quantity)
    end
  end

  def handle_update_error exception
    flash[:alert] = if exception.record == @order
                      t("admin.orders_admin.update.error_with_order",
                        errors: order_errors_message)
                    else
                      t("admin.orders_admin.update.error_with_address")
                    end
    redirect_to edit_admin_order_path(@order), status: :unprocessable_entity
  end

  def order_errors_message
    @order.errors.full_messages.join(", ")
  end

  def filtered_orders
    Order.by_status(params[:status])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_cart_items, only: [:new, :create]
  before_action :set_order, only: [:show]
  before_action :set_user, :logged_in_user, :correct_user,
                only: %i(order_details index cancel)
  before_action :set_order_details, only: %i(order_details)
  before_action :set_order_cancel, only: %i(cancel)

  def new
    @order = Order.new
    @order.total = calculate_cart_total
  end

  def create
    @order = Order.new(order_params)
    @order.user = current_user
    @order.total = calculate_cart_total

    if @order.save
      save_order_items(@order)
      clear_cart
      current_user.send_order_confirm_email @order
      redirect_to order_path(@order)
    else
      flash.now[:alert] = t ".order_fail"
      render :new
    end
  end

  def index
    @orders = @user.orders.with_status(params[:status])

    @pagy, @orders = pagy(
      @orders.ordered_by_updated_at.includes(:address, order_items: :product),
      limit: Settings.ui.address_limit
    )
  end

  def order_details
    render "orders/_order_details"
  end

  def show; end

  def cancel
    cancel_reason = params.dig(:order, :cancel_reason)
    if @order.pending?
      if cancel_reason.present? && @order.update(cancel_reason:,
                                                 status: "cancelled")
        update_cart_items @order
        flash[:success] = t ".order_canceled"
      else
        flash[:danger] = t ".cancel_failed"
      end
    else
      flash[:danger] = t ".cannot_cancel_order"
    end
    redirect_to user_order_order_details_path(@user, @order)
  end

  private
  def set_cart_items
    @cart_items = current_cart_items
  end

  def current_cart_items
    current_user.cart.cart_items.includes(product: :category)
  end

  def set_order
    @order = Order.find_by(id: params[:id])
    return if @order

    flash[:alert] = t ".order_not_found"
    redirect_to root_path
  end

  def order_params
    params.require(:order).permit(
      Order::UPDATE_ORDER
    )
  end

  def calculate_cart_total
    @cart_items.sum{|item| item.product.price * item.quantity}
  end

  def save_order_items order
    @cart_items.each do |item|
      order.order_items.create(product_id: item.product_id,
                               price: item.product.price,
                               quantity: item.quantity)
      if item.product.stock >= item.quantity
        item.product.decrement!(:stock,
                                item.quantity)
      end
    end
  end

  def clear_cart
    current_user.cart.cart_items.destroy_all
  end

  def set_user
    @user = User.find_by id: params[:user_id]
    return if @user

    flash[:danger] = t ".not_found"
    redirect_to root_path
  end

  def set_order_details
    @order = @user.orders
                  .includes(:address, order_items: :product)
                  .find_by(id: params[:order_id])
    return @order_items = @order.order_items.includes(:product) if @order

    flash[:danger] = t ".not_found_order"
    redirect_to root_path
  end

  def set_order_cancel
    @order = @user.orders
                  .includes(:address, order_items: :product)
                  .find_by(id: params[:id])
    return @order_items = @order.order_items.includes(:product) if @order

    flash[:danger] = t ".not_found_order"
    redirect_to root_path
  end

  def update_cart_items order
    cart = current_user.cart || current_user.create_cart
    order.order_items.each do |order_item|
      cart_item = cart.cart_items.find_by(product_id: order_item.product_id)

      if cart_item
        increment_cart_item_quantity(cart_item, order_item)
      else
        create_new_cart_item(cart, order_item)
      end
      @product = Product.find order_item.product_id
      @product.increment! :stock, order_item.quantity
      current_user.send_order_cancel_email @order
    end
  end

  def increment_cart_item_quantity cart_item, order_item
    cart_item.quantity += order_item.quantity
    cart_item.save
  end

  def create_new_cart_item cart, order_item
    cart.cart_items.create!(
      product_id: order_item.product_id, quantity: order_item.quantity
    )
  end
end

app/helpers/admin/orders_helper.rb
module Admin
  module OrdersHelper
    def order_status_label status
      case status.to_sym
      when :pending
        t("orders.status.pending")
      when :confirmed
        t("orders.status.confirmed")
      when :preparing
        t("orders.status.preparing")
      when :delivering
        t("orders.status.delivering")
      when :delivered
        t("orders.status.delivered")
      when :cancelled
        t("orders.status.cancelled")
      else
        t("orders.status.unknown")
      end
    end

    def payment_method_label payment_method
      case payment_method.to_sym
      when :cash_on_delivery
        t("orders.payment_method.cash_on_delivery")
      when :credit_card
        t("orders.payment_method.credit_card")
      else
        t("orders.payment_method.unknown")
      end
    end

    def order_status_class status
      case status.to_sym
      when :pending
        "bg-yellow-100 text-yellow-700"
      when :confirmed
        "bg-blue-100 text-blue-700"
      when :preparing
        "bg-orange-100 text-orange-700"
      when :delivering
        "bg-teal-100 text-teal-700"
      when :delivered
        "bg-green-100 text-green-700"
      when :cancelled
        "bg-red-100 text-red-700"
      else
        "bg-gray-100 text-gray-700"
      end
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def status_color status
    case status.to_sym
    when :pending
      "text-orange-500 bg-orange-200"
    when :confirmed
      "text-purple-500 bg-purple-200"
    when :preparing
      "text-yellow-500 bg-yellow-200"
    when :delivering
      "text-blue-500 bg-blue-200"
    when :delivered
      "text-green-500 bg-green-200"
    when :cancelled
      "text-red-500 bg-red-200"
    else
      "text-gray-500"
    end
  end

  def first_product_image order
    order.order_items.limit(1).first&.product&.image
  end

  def remaining_images_count order
    order.order_items.count - 1
  end

  def product_names order
    order.order_items.limit(3).map{|item| item.product.name}
  end

  def remaining_items_count order
    order.order_items.count - 3
  end

  def order_status_options
    Order.statuses.map do |status, _|
      {label: t("admin.orders_admin.edit.statuses.#{status}"), value: status}
    end
  end
end

app/views/admin/orders/_order_item.html.erb
<tr class="border-b border-gray-200 hover:bg-gray-100">
  <td class="py-3 px-6 text-left whitespace-nowrap">
    <div class="flex items-center">
      <span class="font-medium"><%= index %></span>
    </div>
  </td>

  <td class="py-3 px-6 text-left">
    <%= link_to order.user.user_name, admin_user_path(order.user), class: "text-blue-600 hover:underline" %>
  </td>

  <td class="py-3 px-6 text-left">
    <% if order.address %>
      <%= order.address.full_address %>
    <% else %>
      <span class="text-gray-400 italic">N/A</span>
    <% end %>
  </td>

  <td class="py-3 px-6 text-left">
    <%= payment_method_label(order.payment_method) %>
  </td>

  <td class="py-3 px-6 text-center">
    <span class="py-1 px-3 rounded-full text-xs <%= order_status_class(order.status) %> whitespace-nowrap">
      <%= order_status_label(order.status) %>
    </span>
  </td>

  <td class="py-3 px-6 text-right">
    <%= "#{number_to_currency(order.total, unit: "", precision: 0)} ₫" %>
  </td>

  <td class="py-3 px-6 text-center">
    <%= order.created_at.strftime("%d-%m-%Y") %>
  </td>

  <td class="py-3 px-6 text-center">
    <div class="flex item-center justify-center">
      <%= link_to admin_order_path(order), class: "w-4 mr-2 transform hover:text-blue-600 hover:scale-110" do %>
        <i class="fa fa-eye text-blue-600"></i> 
      <% end %>
      <%= link_to edit_admin_order_path(order), class: "w-4 mr-2 transform hover:text-yellow-600 hover:scale-110" do %>
        <i class="fa fa-edit text-yellow-600"></i>
      <% end %>
    </div>
  </td>
</tr>

app/views/admin/orders/_product_item.html.erb
<tr class="border-b border-gray-200 hover:bg-gray-100">
  <td class="py-3 px-6 text-left">
    <%= image_tag(product_item.product.image, class: "w-20 h-20 object-cover") %>
  </td>
  <td class="py-3 px-6 text-left">
    <%= product_item.product.name %>
  </td>
  <td class="py-3 px-6 text-left">
    <%= product_item.product.category.name %>
  </td>
  <td class="py-3 px-6 text-center">
    <%= product_item.quantity %>
  </td>
  <td class="py-3 px-6 text-right">
    <%= number_to_currency(product_item.product.price, unit: "", precision: 0) %> ₫
  </td>
  <td class="py-3 px-6 text-right">
    <%= number_to_currency(product_item.product.price * product_item.quantity, unit: "", precision: 0) %> ₫
  </td>
</tr>

app/views/admin/orders/edit.html.erb
<div class="h-full ml-14 mb-10 md:ml-64" style="padding-top: 110px;">
  <h1 class="text-4xl font-bold text-gray-800 mb-8 text-center">
    <%= t("admin.orders_admin.edit.title", order_id: @order.id) %> 
  </h1>

  <%= form_with(model: [:admin, @order], local: true) do |f| %>
    <div class="bg-white p-8 rounded-lg shadow-md mb-8">
      <h2 class="text-2xl font-semibold text-gray-700 mb-6 border-b pb-2">
        <%= t("admin.orders_admin.edit.info_title") %> 
      </h2>
      <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div>
          <div class="mb-4">
            <%= f.label "address[receiver_name]", t("admin.orders_admin.edit.receiver_name"), class: "font-medium mb-2" %> 
            <%= f.text_field "address[receiver_name]", value: @order.address.receiver_name, class: "block mt-2 w-full border border-gray-300 rounded-lg px-3 py-2", disabled: @order.cancelled? %>
          </div>
          <div class="mb-4">
            <%= f.label "address[place]", t("admin.orders_admin.edit.address"), class: "font-medium mb-2" %> 
            <%= f.text_field "address[place]", value: @order.address.place, class: "block mt-2 w-full border border-gray-300 rounded-lg px-3 py-2", disabled: @order.cancelled? %>
          </div>
          <div class="mb-4">
            <%= f.label "address[phone]", t("admin.orders_admin.edit.phone"), class: "font-medium mb-2" %> 
            <%= f.text_field "address[phone]", value: @order.address.phone, class: "block mt-2 w-full border border-gray-300 rounded-lg px-3 py-2", disabled: @order.cancelled? %>
          </div>
        </div>
        <div>
          <div class="mb-6">
            <%= f.label :payment_method, t("admin.orders_admin.edit.payment_method"), class: "font-medium text-gray-700" %> 
            <%= f.select :payment_method, 
                  options_for_select([ 
                    [t("admin.orders_admin.edit.payment_methods.cash_on_delivery"), "cash_on_delivery"], 
                    [t("admin.orders_admin.edit.payment_methods.credit_card"), "credit_card"]
                  ], @order.payment_method),
                  {}, 
                  class: "block mt-2 w-full border border-gray-300 rounded-lg px-4 py-3 focus:ring-primary focus:border-primary", 
                  disabled: @order.cancelled? %>
          </div>
          <div class="mb-6">
            <%= f.label :status, t("admin.orders_admin.edit.status"), class: "font-medium text-gray-700" %>
            <%= f.select :status, 
                  options_for_select(order_status_options.map { |status| [status[:label], status[:value]] }, @order.status), 
                  {}, 
                  class: "block mt-2 w-full border border-gray-300 rounded-lg px-4 py-3 focus:ring-primary focus:border-primary", 
                  id: "order-status", 
                  disabled: @order.cancelled? %>
          </div>
          <p class="font-medium text-gray-700 mb-6"><strong><%= t "admin.orders_admin.edit.total" %>:</strong> <%= number_to_currency(@order.total, unit: "", precision: 0) %> ₫</p> 
          <p class="font-medium text-gray-700"><strong><%= t "admin.orders_admin.edit.created_at" %>:</strong> <%= @order.created_at.strftime("%d-%m-%Y") %></p> 
        </div>
      </div>
      <% if @order.cancelled? %>
        <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-6 mt-3">
          <strong><%= t "admin.orders_admin.edit.cancelled_reason" %>:</strong>
          <p><%= @order.cancel_reason %></p>
        </div>
        <p class="text-red-600 mt-2"><%= t "admin.orders_admin.edit.cancelled_status" %></p> 
      <% end %>
      <div class="mt-6">
        <div id="cancel-reason-form" class="mb-4 hidden mt-4">
          <%= f.label :cancel_reason, t("admin.orders_admin.edit.cancel_reason"), class: "font-medium mb-2" %> 
          <%= f.text_area :cancel_reason, class: "block mt-2 w-full border border-gray-300 rounded-lg px-3 py-2", disabled: @order.cancelled? %>
        </div>
      </div>
    </div>
    <div class="mt-8 flex justify-end space-x-4">
      <%= link_to t("admin.orders_admin.edit.cancel"), admin_orders_path, class: "bg-gray-500 hover:bg-gray-600 text-white font-bold py-3 px-6 rounded-lg shadow-md" %> 
      <%= f.submit t("admin.orders_admin.edit.update"), class: "bg-primary hover:bg-primary_hover text-white font-bold py-3 px-6 rounded-lg shadow-md", disabled: @order.cancelled? %> 
    </div>
  <% end %>
  <%= javascript_include_tag "order_status" %>
</div>

app/views/admin/orders/index.html.erb
<div class="h-full ml-14 mb-10 md:ml-64" style="padding-top: 110px;">
  <h1 class="text-3xl font-bold mb-6"><%= t "admin.orders_admin.index.title" %></h1>

  <div class="mb-4 flex justify-between items-center">
    <%= link_to admin_orders_path, class: "text-black hover:text-gray-400" do %>
      <i class="fa fa-sync-alt"></i>
    <% end %>
    <div class="flex-grow mx-4 flex justify-center">
      <%= form_with url: admin_orders_path, method: :get, local: true do %>
        <%= text_field_tag :user_name, params[:user_name], placeholder: t("admin.orders_admin.index.search_by_name"), class: "border rounded-lg py-2 px-4 mr-2" %>
        <%= submit_tag t("admin.orders_admin.index.search"), class: "bg-primary text-white py-2 px-4 rounded-lg hover:bg-primary_hover" %>
      <% end %>
    </div>
    <div>
      <%= label_tag :status, t("admin.orders_admin.index.status"), class: "block text-sm font-medium text-gray-700" %>
      <%= form_with url: admin_orders_path, method: :get, local: true, class: "inline-block" do %>
        <%= select_tag :status, options_for_select([["#{t("admin.orders_admin.index.all_status")}", ""]] + Order.statuses.keys.map { |status| [t("orders.status.#{status}"), status] }, params[:status]), class: "form-select" %>
        <%= submit_tag t("admin.orders_admin.index.filter"), class: "bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700" %>
      <% end %>
    </div>
  </div>

  <table class="min-w-full bg-white border rounded-lg shadow-md overflow-hidden table-fixed">
    <thead>
      <tr class="bg-primary text-white uppercase text-sm leading-normal">
        <th class="py-3 px-6 text-left w-1/12 border-r border-gray-200">
          <%= t "admin.orders_admin.index.order_id" %>
        </th> 
        <th class="py-3 px-6 text-left w-1/12 border-r border-gray-200">
          <%= t "admin.orders_admin.index.user" %>
        </th> 
        <th class="py-3 px-6 text-left w-4/12 border-r border-gray-200">
          <%= t "admin.orders_admin.index.address" %>
        </th> 
        <th class="py-3 px-6 text-left w-2/12 border-r border-gray-200">
          <%= t "admin.orders_admin.index.payment_method" %>
        </th> 
        <th class="py-3 px-6 text-center w-1/12 border-r border-gray-200">
          <%= t "admin.orders_admin.index.status" %>
        </th> 
        <th class="py-3 px-6 text-right w-1/12 border-r border-gray-200">
          <div class="flex justify-between items-center">
            <span class="flex-grow"><%= t "admin.orders_admin.index.total" %></span>
            <%= link_to admin_orders_path(sort: "total", direction: params[:direction] == "asc" ? "desc" : "asc"), class: "text-white hover:text-gray-400 ml-2" do %>
              <i class="fa fa-sort-alpha-<%= params[:direction] == 'asc' ? 'up' : 'down' %>"></i>
            <% end %>
          </div>
        </th> 
        <th class="py-3 px-6 text-center w-1/12 border-r border-gray-200">
          <div class="flex justify-between items-center">
            <span class="flex-grow"><%= t "admin.orders_admin.index.created_at" %></span>
            <%= link_to admin_orders_path(sort: "created_at", direction: params[:direction] == "asc" ? "desc" : "asc"), class: "text-white hover:text-gray-400 ml-2" do %>
              <i class="fa fa-sort-alpha-<%= params[:direction] == 'asc' ? 'up' : 'down' %>"></i>
            <% end %>
          </div>
        </th> 
        <th class="py-3 px-6 text-center w-1/12">
          <%= t "admin.orders_admin.index.actions" %>
        </th> 
      </tr>
    </thead>
    <tbody class="text-gray-600 text-sm font-light">
      <% @orders.each_with_index do |order, index| %>
        <%= render partial: "admin/orders/order_item", locals: { order: order, index: index + 1 } %>
      <% end %>
    </tbody>
  </table>
  <div style="display: flex; justify-content: center;">
    <%= render "pagy/pagy_nav", pagy: @pagy %>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="h-full ml-14 mb-10 md:ml-64" style="padding-top: 110px;">
  <h1 class="text-3xl font-bold mb-6 text-center"><%= t "admin.orders_admin.show.title", order_id: @order.id %></h1> 

  <div class="bg-white p-6 rounded-lg shadow-md mb-6">
    <h2 class="text-xl font-semibold mb-4 border-b pb-2"><%= t "admin.orders_admin.show.order_info" %></h2> 
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
      <div>
        <p class="font-medium mb-2"><strong><%= t "admin.orders_admin.show.receiver" %>:</strong> <%= @order.address.receiver_name %></p> 
        <p class="font-medium mb-2"><strong><%= t "admin.orders_admin.show.address" %>:</strong> <%= @order.address.place %></p> 
        <p class="font-medium mb-2"><strong><%= t "admin.orders_admin.show.phone" %>:</strong> <%= @order.address.phone %></p> 
      </div>
      <div>
        <p class="font-medium mb-2"><strong><%= t "admin.orders_admin.show.payment_method" %>:</strong> <%= payment_method_label(@order.payment_method) %></p> 
        <p class="font-medium mb-2">
          <strong><%= t "admin.orders_admin.show.status" %>:</strong>
          <span class="py-1 px-3 rounded-full text-xs <%= order_status_class(@order.status) %>">
            <%= order_status_label(@order.status) %>
          </span>
        </p>
        <p class="font-medium mb-2"><strong><%= t "admin.orders_admin.show.created_at" %>:</strong> <%= @order.created_at.strftime("%d-%m-%Y") %></p> 
        <p class="font-medium mb-2"><strong><%= t "admin.orders_admin.show.total" %>:</strong> <%= number_to_currency(@order.total, unit: "", precision: 0) %> ₫</p> 
      </div>
    </div>

    <% if @order.cancelled? %>
      <div class="mt-4 p-4 bg-red-100 border border-red-400 text-red-700 rounded">
        <strong><%= t "admin.orders_admin.show.cancelled_reason" %></strong> <%= @order.cancel_reason %>
      </div>
    <% end %>
  </div>

  <h2 class="text-xl font-semibold mb-4"><%= t "admin.orders_admin.show.products_in_order" %></h2> 
  <table class="min-w-full bg-white border rounded-lg shadow-md overflow-hidden table-fixed">
    <thead>
      <tr class="bg-primary text-white uppercase text-sm leading-normal">
        <th class="py-3 px-6 text-left"><%= t "admin.orders_admin.show.image" %></th> 
        <th class="py-3 px-6 text-left"><%= t "admin.orders_admin.show.product_name" %></th> 
        <th class="py-3 px-6 text-left"><%= t "admin.orders_admin.show.category" %></th> 
        <th class="py-3 px-6 text-center"><%= t "admin.orders_admin.show.quantity" %></th> 
        <th class="py-3 px-6 text-right"><%= t "admin.orders_admin.show.price" %></th> 
        <th class="py-3 px-6 text-right"><%= t "admin.orders_admin.show.total_price" %></th> 
      </tr>
    </thead>
    <tbody class="text-gray-600 text-sm font-light">
      <%= render partial: "product_item", collection: @order.order_items, as: :product_item %>
    </tbody>
  </table>

  <div class="mt-6 flex justify-end space-x-4">
    <%= link_to t("admin.orders_admin.show.edit"), edit_admin_order_path(@order), class: "bg-primary hover:bg-primary_hover text-white font-bold py-2 px-4 rounded-lg" %> 
    <%= link_to t("admin.orders_admin.show.back"), admin_orders_path, class: "bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded-lg" %> 
  </div>
</div>