config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/static_pages/home"
    get "/static_pages/help"
    get "/static_pages/contact"

    get "/categories/index"
    get "/categories/show"

    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    
    get "/search", to: "search#index"

    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    devise_for :users
    as :user do
      get "signin" => "devise/sessions#new"   
      post "signin" => "devise/sessions#create" 
      delete "signout" => "devise/sessions#destroy"
    end
    resources :users do
      resources :addresses, except: :show
      resources :orders, only: %i(index order_details) do
        get 'order_details', to: 'orders#order_details', as: :order_details
        member do
          patch :cancel
        end
        resources :products, only: [] do
          resources :reviews, only: %i(new create edit update destroy)
        end
        collection do
          get :status, action: :index
        end
      end
      resources :notifications, only: [] do
        member do
          patch :mark_as_read
        end
      end
    end
    resources :categories do
      resources :products
    end
    resources :carts, only: :show do
      post "add_item", on: :collection
      member do
        post "increment_item"
        post "decrement_item"
        delete "remove_item"
      end
    end
    resources :products, only: %i(show index)
    resources :password_resets, only: %i(new create edit update)
    resources :orders, only: %i(new create show) 
    namespace :admin do
      get "profile", to: "dashboard#profile", as: "profile"
      get "dashboard", to: "dashboard#index", as: "dashboard"
      resources :orders
      resources :users do
        member do
          patch :toggle_activation
        end
      end
      resources :products
      resources :categories
      resources :reviews
    end
  end
end

app/views/shared/_breadcrumb.html.erb
<p><%= t ".home" %> / <span class="font-bold"><%= path %></span></p>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="flex p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-50" role="alert">
    <svg class="flex-shrink-0 inline w-4 h-4 me-3 mt-[2px]" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
      <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
    </svg>
    <div>
      <span class="font-medium"><%= t ".the_form_contains" %> <%= pluralize object.errors.count, t(".error") %>.</span>
      <ul class="mt-1.5 list-disc list-inside">
        <% object.errors.full_messages.each do |msg| %>
          <li class="text-red-500"><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_profile_breadcrumb.html.erb
<div class="mb-[50px] text-sm flex justify-between items-center">
  <%= render "shared/breadcrumb", path: t(".my_account") %>
  <p><%= t ".welcome" %>! <span class="text-primary"><%= @user.user_name %></span></p>
</div>

app/views/shared/_profile_sidebar.html.erb
<aside class="flex flex-col gap-[10px]">
  <section class="flex gap-[20px] items-center">
    <%= user_avatar @user, class: "w-[120px] h-[120px] rounded-full" %>
    <h1><%= @user.user_name %></h1>
  </section>
  <ul>
    <h2 class="font-bold"><%= t ".manage_account" %></h2>
    <li class="ml-[20px] mt-[10px] <%= current_page?(edit_user_path(@user)) ? "text-primary" : "" %>">
      <%= link_to t(".profile"), edit_user_path(@user) %>
    </li>
    <li class="ml-[20px] mt-[10px] <%= current_page?(user_addresses_path(@user)) ? "text-primary" : "" %>">
      <%= link_to t(".address"), user_addresses_path(@user) %>
    </li>
  </ul>
  <%= link_to user_orders_path(current_user), class: "flex items-center gap-2" do %>
    <h2 class="font-bold"><%= t ".order" %></h2>
  <% end %>
</aside>