config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/static_pages/home"
    get "/static_pages/help"
    get "/static_pages/contact"

    get "/categories/index"
    get "/categories/show"

    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    
    get "/search", to: "search#index"

    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    devise_for :users
    as :user do
      get "signin" => "devise/sessions#new"   
      post "signin" => "devise/sessions#create" 
      delete "signout" => "devise/sessions#destroy"
    end
    resources :users do
      resources :addresses, except: :show
      resources :orders, only: %i(index order_details) do
        get 'order_details', to: 'orders#order_details', as: :order_details
        member do
          patch :cancel
        end
        resources :products, only: [] do
          resources :reviews, only: %i(new create edit update destroy)
        end
        collection do
          get :status, action: :index
        end
      end
      resources :notifications, only: [] do
        member do
          patch :mark_as_read
        end
      end
    end
    resources :categories do
      resources :products
    end
    resources :carts, only: :show do
      post "add_item", on: :collection
      member do
        post "increment_item"
        post "decrement_item"
        delete "remove_item"
      end
    end
    resources :products, only: %i(show index)
    resources :password_resets, only: %i(new create edit update)
    resources :orders, only: %i(new create show) 
    namespace :admin do
      get "profile", to: "dashboard#profile", as: "profile"
      get "dashboard", to: "dashboard#index", as: "dashboard"
      resources :orders
      resources :users do
        member do
          patch :toggle_activation
        end
      end
      resources :products
      resources :categories
      resources :reviews
    end
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :logged_in_user,
                :set_cart,
                only: %i(show
                        add_item
                        increment_item
                        decrement_item
                        remove_item)
  before_action :set_product_and_quantity, only: :add_item
  before_action :set_user, :correct_user, only: %i(show)
  before_action :find_cart_item,
                only: %i(increment_item
                        decrement_item
                        remove_item)

  def show
    cart_items_query = @cart.cart_items.includes(product: :category)
    @pagy, @cart_items = pagy cart_items_query, limit: Settings.ui.cart_items
    calculate_total
  end

  def add_item
    @cart_item = @cart.cart_items.find_by product_id: @product_id
    if @cart_item.nil?
      add_new_item_to_cart
    else
      update_existing_cart_item
    end
    calculate_total
    respond_to do |format|
      format.html{redirect_to product_path(@product)}
      format.turbo_stream
    end
  end

  def increment_item
    if can_increment_item?
      increment_cart_item
    else
      flash.now[:error] = t "carts.insufficient_stock"
    end
    calculate_total
    respond_to do |format|
      format.html{redirect_to cart_path(@cart)}
      format.turbo_stream
    end
  end

  def decrement_item
    if can_decrement_item?
      decrement_cart_item
    else
      remove_cart_item
    end
    calculate_total
    respond_to do |format|
      format.html{redirect_to cart_path(@cart)}
      format.turbo_stream
    end
  end

  def remove_item
    @cart_item.destroy
    flash.now[:success] = t "carts.item_removed_success"
    calculate_total
    respond_to do |format|
      format.html{redirect_to cart_path(@cart)}
      format.turbo_stream
    end
  end

  private
  def set_cart
    @cart = current_user.cart || current_user.create_cart
  end

  def set_user
    cart = Cart.find_by id: params[:id]
    return @user = cart.user if cart.present?

    flash[:danger] = t "carts.cart_not_found"
    redirect_to root_path
  end

  def set_product_and_quantity
    @quantity = params[:quantity].to_i
    @product_id = params[:product_id]
    @product = Product.find_by id: @product_id
    return if @product

    flash[:danger] = t "carts.product_not_found"
    redirect_to root_path
  end

  def find_cart_item
    @cart_item = @cart.cart_items.find_by id: params[:id]
    return @product = @cart_item.product if @cart_item.present?

    flash[:danger] = t "carts.cart_item_not_found"
    redirect_to root_path
  end

  def add_new_item_to_cart
    if @quantity > @product.stock
      flash.now[:error] = t "carts.insufficient_stock"
    else
      @cart_item = @cart.cart_items.build(
        product_id: @product.id,
        quantity: @quantity
      )
      if @cart_item.save
        flash.now[:success] = t "carts.item_added_success"
      else
        flash.now[:danger] = t "carts.item_added_error"
      end
    end
  end

  def update_existing_cart_item
    new_quantity = @cart_item.quantity + @quantity
    if new_quantity > @product.stock + @cart_item.quantity
      flash.now[:error] = t "carts.insufficient_stock"
    elsif @cart_item.update(quantity: new_quantity)
      flash.now[:success] = t "carts.item_added_success"
    else
      flash.now[:danger] = t "carts.item_added_error"
    end
  end

  def can_increment_item?
    @product.stock >= 1
  end

  def increment_cart_item
    @cart_item.quantity += 1
    if @cart_item.save
      flash.now[:success] = t "carts.item_increment_success"
    else
      flash.now[:error] = t "carts.insufficient_stock"
    end
  end

  def can_decrement_item?
    @cart_item.quantity > 1
  end

  def decrement_cart_item
    @cart_item.quantity -= 1
    if @cart_item.save
      flash.now[:success] = t "carts.item_decrement_success"
    else
      flash.now[:error] = t "carts.insufficient_stock"
    end
  end

  def remove_cart_item
    @cart_item.quantity = 0
    @cart_item.destroy
    flash.now[:success] = t "carts.item_removed_success"
  end

  def calculate_total
    cart_items_with_price = @cart.cart_items.includes(:product)
    @total = cart_items_with_price.sum("cart_items.quantity * products.price")
  end

  def current_cart_items
    @cart.cart_items.includes(product: :category)
  end
end

app/views/carts/_cart_item.html.erb
<div id="cart-item-<%= cart_item.id %>" class="grid grid-cols-12 gap-3 py-4 border-b-primary border-b-solid border-b-[1px]">
  <div class="col-span-3">
    <figure class="h-[200px] rounded-lg overflow-hidden object-contain">
      <%= image_tag cart_item.product.image, alt: cart_item.product.name, class: "h-full" %>
    </figure>
  </div>
  <div class="col-span-6">
    <h2 class="text-xl font-bold">
      <%= link_to cart_item.product.name, product_path(cart_item.product), class: "hover:underline" %>
    </h2>
    <p class="flex gap-2 mt-5"><span class="text-primary"><%= t ".category" %>:</span><%= cart_item.product.category.name %></p>
  </div>
  <div class="col-span-3 flex flex-col justify-between gap-3 items-center border-l-[1px] border-l-solid border-l-primary">
    <p class="text-xl font-bold"><%= "#{number_to_currency(cart_item.product.price, unit: "", precision: 0)} ₫" %></p>
    <div class="flex items-center space-x-4" data-controller="quantity">
      <%= button_to decrement_item_cart_path(cart_item), method: :post, class: "flex items-center justify-center w-8 h-8 border border-gray-300 rounded-full hover:bg-gray-200 focus:outline-none" do %>
        <span class="text-lg">-</span>
      <% end %>
      <p id="cart-item-<%= cart_item.id %>-quantity"><%= cart_item.quantity %></p>
      <%= button_to increment_item_cart_path(cart_item), method: :post, class: "flex items-center justify-center w-8 h-8 border border-gray-300 rounded-full hover:bg-gray-200 focus:outline-none" do %>
        <span class="text-lg">+</span>
      <% end %>
    </div>
    <%= button_to remove_item_cart_path(cart_item), method: :delete, class: "flex items-center text-xl text-primary gap-5" do %>
      <i class="fa-solid fa-trash"></i>
      <p class="text-base"><%= t ".remove" %></p>
    <% end %>
  </div>
</div>

app/views/carts/_empty_cart.html.erb
<div class="flex flex-col items-center justify-center gap-5">
  <%= image_tag "empty-cart.png", alt: "", class: "w-[300px] h-[300px] mx-auto" %>
  <p class="text-2xl font-bold"><%= t ".empty_cart" %></p>
</div>

app/views/carts/add_item.turbo_stream.erb
<%= turbo_stream.update "cart-items" do %>
  <%= @cart.cart_items.count %>
<% end %>
<%= turbo_stream.replace "flash-messages", partial: "layouts/notification" %>
<%= turbo_stream.update "cart-price" do %>
  <%= @total %>
<% end %>
<%= turbo_stream.update "total-price" do %>
  <%= @total %>
<% end %>
<%= turbo_stream.update "cart-items-quantity" do %>
  <%= @cart.cart_items.count %>
<% end %>
<%= turbo_stream.replace "quantity-input" do %>
  <%= render "products/cart_form" %>
<% end %>

app/views/carts/decrement_item.turbo_stream.erb
<% if @cart.cart_items.empty? %>
  <%= turbo_stream.replace "cart", partial: "carts/empty_cart" %>
<% else %>
  <% if @cart_item.quantity == 0 %>
    <%= turbo_stream.remove "cart-item-#{@cart_item.id}" %>
  <% else %>
    <%= turbo_stream.update "cart-item-#{@cart_item.id}-quantity" do %>
      <%= @cart_item.quantity %>
    <% end %>
  <% end %>
  <%= turbo_stream.update "cart-price" do %>
    <%= @total %>
  <% end %>
  <%= turbo_stream.update "total-price" do %>
    <%= @total %>
  <% end %>
  <%= turbo_stream.update "cart-items-quantity" do %>
    <%= @cart.cart_items.count %>
  <% end %>
<% end %>
<%= turbo_stream.replace "flash-messages", partial: "layouts/notification" %>
<%= turbo_stream.update "cart-items" do %>
  <%= @cart.cart_items.count %>
<% end %>

app/views/carts/increment_item.turbo_stream.erb
<%= turbo_stream.update "cart-item-#{@cart_item.id}-quantity" do %>
  <%= @cart_item.quantity %>
<% end %>
<%= turbo_stream.replace "flash-messages", partial: "layouts/notification" %>
<%= turbo_stream.update "cart-price" do %>
  <%= @total %>
<% end %>
<%= turbo_stream.update "total-price" do %>
  <%= @total %>
<% end %>
<%= turbo_stream.update "cart-items-quantity" do %>
  <%= @cart.cart_items.count %>
<% end %>

app/views/carts/remove_item.turbo_stream.erb
<% if @cart.cart_items.empty? %>
  <%= turbo_stream.replace "cart", partial: "carts/empty_cart" %>
<% else %>
  <%= turbo_stream.remove "cart-item-#{@cart_item.id}" %>
  <%= turbo_stream.update "cart-price" do %>
    <%= @total %>
  <% end %>
  <%= turbo_stream.update "total-price" do %>
    <%= @total %>
  <% end %>
  <%= turbo_stream.update "cart-items-quantity" do %>
    <%= @cart.cart_items.count %>
  <% end %>
<% end %>
<%= turbo_stream.replace "flash-messages", partial: "layouts/notification" %>
<%= turbo_stream.update "cart-items" do %>
  <%= @cart.cart_items.count %>
<% end %>

app/views/carts/show.html.erb
<% if @cart_items.empty? %>
  <%= render "empty_cart" %>
<% else %>
  <div id="cart" class="grid grid-cols-12 gap-5">
    <div class="col-span-8 bg-white drop-shadow-lg p-5 rounded-lg">
      <%= render partial: "carts/cart_item", collection: @cart_items %>
      <div class="mt-3">
        <%== pagy_nav(@pagy) %>
      </div>
    </div>
    <div class="col-span-4 bg-white drop-shadow-lg rounded-lg p-[20px] h-[180px]">
      <div class="flex justify-between">
        <p class="text-base"><span class="text-base font-bold"><%= t ".subtotal" %></span> (<%= t ".items" %>)</p>
        <p id="cart-items-quantity"><%= @cart_items.count %></p>
      </div>
      <div class="flex justify-between">
        <p class="text-base"><span class="text-base font-bold"><%= t ".price" %></span> (<%= t ".total" %>)</p>
        <p id="cart-price"><%= "#{number_to_currency(@total, unit: "", precision: 0)} ₫" %></p>
      </div>
      <div class="flex justify-between">
        <span class="text-base font-bold"><%= t ".shipping" %></span>
        <p><%= t ".free" %></p>
      </div>
      <div class="w-full h-[1px] bg-primary my-3"></div>
      <div class="flex justify-between">
        <p class="text-base font-bold"><%= t ".total" %></p>
        <p id="total-price"><%= "#{number_to_currency(@total, unit: "", precision: 0)} ₫" %></p>
      </div>
      <div class="mt-4 flex justify-center">
        <%= button_to t(".order"), new_order_path, method: :get, class: "bg-primary text-white px-6 py-2 rounded-md hover:bg-primary_hover" %>
      </div>
    </div>
  </div>
<% end %>